services:
  db:
    container_name: 'local-wordpress-db'
    image: 'mysql:8.0'
    restart: always
    volumes:
      - db_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      retries: 3
    ports:
      - "3306:3306"

  wordpress:
    container_name: 'local-wordpress'
    depends_on:
      db:
        condition: service_healthy
    image: 'wordpress:6.4' # Use a stable version instead of latest
    restart: always
    ports:
      - "666:80"
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: ${MYSQL_USER}
      WORDPRESS_DB_PASSWORD: ${MYSQL_PASSWORD}
      WORDPRESS_DB_NAME: ${MYSQL_DATABASE}
    volumes:
      - "./wordpress:/var/www/html"
      - "./themes:/var/www/html/wp-content/themes"
      - "./plugins:/var/www/html/wp-content/plugins"

volumes:
  db_data:
